// <auto-generated />
namespace REMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Complexes_name_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Complexes_name_add));
        
        string IMigrationMetadata.Id
        {
            get { return "201708280719515_Complexes_name_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
